import torch
from cgfn.model import ContinuousRNN
from ccat > update.sh <<'OUTER'
#!/usr/bin/env bash
set -e

echo "=== Neue Datei: src/cgfn/effdim.py (Effective Dimension) ==="
cat > src/cgfn/effdim.py <<'EOF'
"""
Effective Dimension als geometrisches Generalisierungsmaß.
Basierend auf 'On the Relationship Between Representation Geometry
and Generalization in Deep Neural Networks' (2026).
Misst die intrinsische Dimension der Repräsentationsmannigfaltigkeit.
"""
import torch


@torch.no_grad()
def effective_dimension(states, threshold=0.99):
    """
        states: (n, H) Repräsentationen.
            Schätzt die effektive Dimension über die Singulärwerte der
                zentrierten Datenmatrix. threshold: kumulativer Varianzanteil.
                    """
                        X = states - states.mean(dim=0, keepdim=True)
                            # SVD
                                try:
                                        S = torch.linalg.svdvals(X)
                                            except Exception:
                                                    return float('nan')
                                                        S2 = S ** 2
                                                            total = S2.sum()
                                                                if total <= 0:
                                                                        return 0.0
                                                                            cum = torch.cumsum(S2, dim=0) / total
                                                                                d_eff = (cum < threshold).sum().item() + 1
                                                                                    return float(d_eff)
                                                                                    
                                                                                    
                                                                                    @torch.no_grad()
                                                                                    def effective_dimension_ratio(states):
                                                                                        """Verhältnis effektive Dimension / nominale Dimension."""
                                                                                            d_eff = effective_dimension(states)
                                                                                                H = states.shape[-1]
                                                                                                    return d_eff / H
                                                                                                    EOF
                                                                                                    
                                                                                                    echo
                                                                                                    echo "=== Neue Datei: src/cgfn/inputdsa.py (InputDSA-Stub) ==="
                                                                                                    cat > src/cgfn/inputdsa.py <<'EOF'
                                                                                                    """
                                                                                                    InputDSA: Trennt intrinsische Dynamik von input-getriebener Dynamik.
                                                                                                    Basierend auf 'InputDSA: Demixing then comparing recurrent and externally
                                                                                                    driven dynamics' (ICLR 2026).
                                                                                                    Vereinfachte Implementierung: Lineare DMDc-Schätzung.
                                                                                                    """
                                                                                                    import torch
                                                                                                    
                                                                                                    
                                                                                                    @torch.no_grad()
                                                                                                    def estimate_dynamics(model, task, seq_len=8, batch=32, device="cpu"):
                                                                                                        """Schätzt intrinsische (A) und input-getriebene (B) Dynamik.
                                                                                                            Modell: dz/dt = f(z, x). Lineare Näherung: z_next ≈ A z + B x."""
                                                                                                                from cgfn.tasks import make_batch, TASKS
                                                                                                                    x, _ = make_batch(task, batch_size=batch, seq_len=seq_len, device=device)
                                                                                                                        if hasattr(model, 'task_dim') and model.task_dim > 0:
                                                                                                                                idx = TASKS.index(task)
                                                                                                                                        tv = torch.zeros(batch, model.task_dim, device=device)
                                                                                                                                                tv[:, idx] = 1.0
                                                                                                                                                        _, states = model(x, tv)
                                                                                                                                                            else:
                                                                                                                                                                    _, states = model(x)
                                                                                                                                                                        if states.dim() == 4:
                                                                                                                                                                                states = states.squeeze(0)
                                                                                                                                                                                    H = states.shape[-1]
                                                                                                                                                                                        z = states[:, :-1, :].reshape(-1, H)
                                                                                                                                                                                            z_next = states[:, 1:, :].reshape(-1, H)
                                                                                                                                                                                                x_flat = x[:, :-1, :].reshape(-1, x.shape[-1])
                                                                                                                                                                                                    # Design-Matrix [z, x]
                                                                                                                                                                                                        D = torch.cat([z, x_flat], dim=-1)
                                                                                                                                                                                                            # Ridge-Regression: [A B] = (D^T D + λI)^-1 D^T z_next
                                                                                                                                                                                                                lam = 1e-3
                                                                                                                                                                                                                    DtD = D.T @ D + lam * torch.eye(D.shape[1], device=device)
                                                                                                                                                                                                                        Dtz = D.T @ z_next
                                                                                                                                                                                                                            W = torch.linalg.solve(DtD, Dtz)
                                                                                                                                                                                                                                A = W[:H, :].T
                                                                                                                                                                                                                                    B = W[H:, :].T
                                                                                                                                                                                                                                        return A, B
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                        @torch.no_grad()
                                                                                                                                                                                                                                        def inputdsa(A1, B1, A2, B2):
                                                                                                                                                                                                                                            """Vergleicht intrinsische und input-getriebene Dynamik.
                                                                                                                                                                                                                                                Rückgabe: (dsa_intrinsic, dsa_input)."""
                                                                                                                                                                                                                                                    def norm_diff(X, Y):
                                                                                                                                                                                                                                                            num = ((X - Y) ** 2).mean().sqrt()
                                                                                                                                                                                                                                                                    den = (X ** 2).mean().sqrt() + (Y ** 2).mean().sqrt() + 1e-12
                                                                                                                                                                                                                                                                            return (num / den).item()
                                                                                                                                                                                                                                                                                return norm_diff(A1, A2), norm_diff(B1, B2)
                                                                                                                                                                                                                                                                                EOF
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                echo
                                                                                                                                                                                                                                                                                echo "=== Neues Experiment: Effektive Dimension + InputDSA + Tau-Sweep ==="
                                                                                                                                                                                                                                                                                cat > experiments/frontier2.py <<'EOF'
                                                                                                                                                                                                                                                                                import torch
                                                                                                                                                                                                                                                                                from itertools import combinations
                                                                                                                                                                                                                                                                                from cgfn.model import ContinuousRNN
                                                                                                                                                                                                                                                                                from cgfn.tasks import TASKS, make_batch
                                                                                                                                                                                                                                                                                from cgfn.cka import cka
                                                                                                                                                                                                                                                                                from cgfn.effdim import effective_dimension, effective_dimension_ratio
                                                                                                                                                                                                                                                                                from cgfn.inputdsa import estimate_dynamics, inputdsa
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                device = "cpu"
                                                                                                                                                                                                                                                                                task_dim = len(TASKS)
                                                                                                                                                                                                                                                                                SEQ_LEN = 8
                                                                                                                                                                                                                                                                                HIDDEN = 32
                                                                                                                                                                                                                                                                                STEPS = 2000
                                                                                                                                                                                                                                                                                SEEDS = [0, 1, 2]
                                                                                                                                                                                                                                                                                TASK_SUBSET = ["copy", "reverse", "parity", "mod3"]
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                def one_hot(task_idx, batch_size):
                                                                                                                                                                                                                                                                                    v = torch.zeros(batch_size, task_dim, device=device)
                                                                                                                                                                                                                                                                                        v[:, idx] = 1.0
                                                                                                                                                                                                                                                                                            return v
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                            def train(seed, task, tau=1.0, steps=STEPS, lr=1e-3):
                                                                                                                                                                                                                                                                                                torch.manual_seed(seed)
                                                                                                                                                                                                                                                                                                    model = ContinuousRNN(task_dim=task_dim, hidden_dim=HIDDEN, tau=tau)
                                                                                                                                                                                                                                                                                                        opt = torch.optim.Adam(model.parameters(), lr=lr)
                                                                                                                                                                                                                                                                                                            lossfn = torch.nn.BCEWithLogitsLoss()
                                                                                                                                                                                                                                                                                                                idx = TASKS.index(task)
                                                                                                                                                                                                                                                                                                                    for _ in range(steps):
                                                                                                                                                                                                                                                                                                                            x, y = make_batch(task, seq_len=SEQ_LEN, device=device)
                                                                                                                                                                                                                                                                                                                                    tv = one_hot(idx, x.shape[0])
                                                                                                                                                                                                                                                                                                                                            out, _ = model(x, tv)
                                                                                                                                                                                                                                                                                                                                                    loss = lossfn(out, y)
                                                                                                                                                                                                                                                                                                                                                            opt.zero_grad(); loss.backward(); opt.step()
                                                                                                                                                                                                                                                                                                                                                                return model, loss.item()
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                def reps(model, task, fixed_x):
                                                                                                                                                                                                                                                                                                                                                                    idx = TASKS.index(task)
                                                                                                                                                                                                                                                                                                                                                                        tv = one_hot(idx, fixed_x.shape[0])
                                                                                                                                                                                                                                                                                                                                                                            with torch.no_grad():
                                                                                                                                                                                                                                                                                                                                                                                    _, s = model(fixed_x, tv)
                                                                                                                                                                                                                                                                                                                                                                                        if s.dim() == 4:
                                                                                                                                                                                                                                                                                                                                                                                                s = s.squeeze(0)
                                                                                                                                                                                                                                                                                                                                                                                                    B, T, H = s.shape
                                                                                                                                                                                                                                                                                                                                                                                                        return s.reshape(B * T, H)
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                        def main():
                                                                                                                                                                                                                                                                                                                                                                                                            torch.manual_seed(999)
                                                                                                                                                                                                                                                                                                                                                                                                                x_fixed = torch.randint(0, 2, (32, SEQ_LEN, 1), device=device).float()
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                    print("=" * 70)
                                                                                                                                                                                                                                                                                                                                                                                                                        print("FRONTIER 2: Effective Dimension + InputDSA + Tau-Sweep")
                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"seeds={SEEDS}  tasks={TASK_SUBSET}  hidden_dim={HIDDEN}")
                                                                                                                                                                                                                                                                                                                                                                                                                                print("=" * 70)
                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                    # ─── A) Effective Dimension ───
                                                                                                                                                                                                                                                                                                                                                                                                                                        print("\n--- A) Effective Dimension (hoeher = reichere Geometrie) ---")
                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"{'task':10s} {'seed':>4s} {'loss':>8s} {'d_eff':>7s} {'ratio':>7s}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                all_d_eff = {t: [] for t in TASK_SUBSET}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    for task in TASK_SUBSET:
                                                                                                                                                                                                                                                                                                                                                                                                                                                            for seed in SEEDS:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        m, loss = train(seed, task)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    r = reps(m, task, x_fixed)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                d = effective_dimension(r)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ratio = effective_dimension_ratio(r)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        all_d_eff[task].append(d)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"{task:10s} {seed:4d} {loss:8.4f} {d:7.2f} {ratio:7.3f}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("\n  Mittelwerte:")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for task in TASK_SUBSET:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    vals = all_d_eff[task]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mean = sum(vals) / len(vals)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"    {task:10s}: d_eff={mean:.2f}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # ─── B) InputDSA ───
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("\n--- B) InputDSA: intrinsische vs input-getriebene Dynamik ---")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"{'task':10s} {'seed':>4s} {'loss':>8s} {'dsa_int':>8s} {'dsa_inp':>8s}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for task in TASK_SUBSET:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for seed in SEEDS:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        m, loss = train(seed, task)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    A, B = estimate_dynamics(m, task, device=device)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    d_int = A.norm().item()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    d_inp = B.norm().item()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"{task:10s} {seed:4d} {loss:8.4f} {d_int:8.4f} {d_inp:8.4f}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"{task:10s} {seed:4d} {loss:8.4f} ERROR: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # ─── C) Tau-Sweep ───
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("\n--- C) Tau-Sweep: Effekt der Rückstellkraft auf Kollaps ---")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            taus = [0.1, 0.5, 1.0, 2.0, 5.0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"{'tau':>6s} {'copy_loss':>10s} {'parity_loss':>12s} {'mod3_loss':>10s} {'CKA(copy,parity)':>18s}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for tau in taus:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            losses = {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reps_dict = {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for task in ["copy", "parity", "mod3"]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        m, loss = train(0, task, tau=tau, steps=1500)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    losses[task] = loss
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                reps_dict[task] = reps(m, task, x_fixed)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cka_cp = cka(reps_dict["copy"], reps_dict["parity"], kernel="linear")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"{tau:6.1f} {losses['copy']:10.4f} {losses['parity']:12.4f} "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              f"{losses['mod3']:10.4f} {cka_cp:18.4f}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  print("\n=== FERTIG ===")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      main()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      EOF
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo "=== Syntax-Check ==="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      for f in src/cgfn/effdim.py src/cgfn/inputdsa.py experiments/frontier2.py; do
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          python -c "import ast; ast.parse(open('$f').read())" 2>&1 \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                && echo "OK: $f" \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      || echo "FAIL: $f"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      done
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo "=== Lauf (15-30 min) ==="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      python experiments/frontier2.py 2>&1 | tee frontier2_results.txt
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo "=== Fertig: frontier2_results.txt ==="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      OUTER
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      chmod +x update.sh
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ./update.sh
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      gfn.tasks import make_batch
from cgfn.criticality import jacobian_spectral_radius


def test_forward_shape():
    m = ContinuousRNN()
    x, _ = make_batch("copy", batch_size=4, seq_len=8)
    out, states = m(x)
    assert out.shape == (4, 8, 1)
    assert states.shape == (4, 8, 32)


def test_spectral_radius_finite():
    m = ContinuousRNN()
    x, _ = make_batch("copy", batch_size=4, seq_len=8)
    with torch.no_grad():
        _, s = m(x)
    sr = jacobian_spectral_radius(m, s[:, -1])
    assert torch.isfinite(sr).all()
